name: build recovery
on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build-recovery:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:

    - name: "Checkout Repo"
      uses: actions/checkout@v4

    # Cleanup The Actions Workspace Using Custom Composite Run Actions
    - name: Free Disk Space
      uses: rokibhasansagar/slimhub_actions@main
      # That's it! Now use your normal steps

    - name: Install Build Tools
      uses: daaku/gh-action-apt-install@v4
      with:
        packages: dos2unix gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 python

    - name: Install OpenJDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Setup ccache

      uses: hendrikmuhs/ccache-action@main
      with:
        max-size: 4G

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
         python-version: '3.10'

    - name: Install repo
      run: |
        mkdir ~/bin
        ls
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo

    - name: Initialize repo
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "Nico170420"
        git config --global user.email "b170420nc@gmail.com"
        python3 ~/bin/repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1
      id: pwd

    - name: Repo Sync
      run: |
        python3 ~/bin/repo sync -j$(nproc --all) --force-sync
      working-directory: workspace

    - run: sudo du -h workspace
      continue-on-error: true

    - run: sudo df -h
      continue-on-error: true

    - name: Clone device tree
      run: |
        git clone https://github.com/dabao1955/twrp_device_oppo_PDRM00 -b oss-S ./device/oppo/PDRM00
      working-directory: workspace

    - name: Sync Device Dependencies
      run: |
        bash ${GITHUB_WORKSPACE}/.github/scripts/convert.sh device/oppo/PDRM00/twrp.dependencies
        ~/bin/repo sync -j$(nproc --all)
      working-directory: workspace
      continue-on-error: true

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 16

    - name: Building recovery
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch twrp_PDRM00-eng && make clean && make recoveryimage -j$(nproc --all)
      working-directory: workspace

    - run: sudo du -h workspace
      continue-on-error: true

    - run: sudo df -h
      continue-on-error: true

    - run: sudo du -h workspace/out
      continue-on-error: true

    - name: Upload recovery.img to Artifact
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v3
      with:
       name: "recovery.zip"
       path: workspace/out/target/product/PDRM00/recovery.img
